### ISSUE TITLE
Runit problem - timeout: down: anbox-container-manager: 1s, normally up, want up

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Luciogi/artix_pkg#2]
After in installed runit service for anbox and i made a soft link as it said after package installed

each time i try to start service it throws timeout error

**Comment by Luciogi** [comment]
It should work fine once service is started.
Sorry I can't test at the time

**Comment by EsmailELBoBDev2** [comment]
oh I forgot to close this issue....
About how I solved it, I restarted my computer 

But now i face another problem not sure if it's related to your package or anbox itself, https://github.com/anbox/anbox/issues/1988

**Comment by Luciogi** [comment]
Issue fixed in https://github.com/Luciogi/artix_pkg/commit/bd93bb5bc34362cdccbd71b3765fa64f15f7f8fe
